### ISSUE TITLE
Code not compatible with PHP 7.4

### ISSUE THREAD

**Issue by knit-pay** [pronamic/wp-pay-core#133]
Hello Team

The below code is not compatible with PHP version 7.4. May I raise a pull request to fix it?

https://github.com/pronamic/wp-pay-core/blob/b55dff3f073c56f5780522a78f6412823b519e7a/views/meta-box-gateway-settings.php#L80

**Comment by rvdsteege** [comment]
Polyfills for `str_starts_with()` and `str_ends_with()` have been included in WordPress since WordPress version 5.9. Therefore, we also mention in our plugin file that WordPress 5.9+ is required:
- https://github.com/pronamic/wp-pronamic-pay/blob/d110fb2ca595c1e743ba3c9aa57e193a5e9ddd98/pronamic-ideal.php#L8.

I don't think there's any need to otherwise update the code.
