### ISSUE TITLE
`PaymentInfo::get_meta()` results in empty string due to `get_post_meta()` fallback

### ISSUE THREAD

**Issue by rvdsteege** [pronamic/wp-pay-core#163]
There is an issue with starting first payments with some integrations since the Pronamic Pay 9.6 release. This has to do with recent changes in setting the Mollie sequence type:
- https://github.com/pronamic/wp-pronamic-pay-woocommerce/issues/58

The underlying issue is `PaymentInfo::get_meta()` falling back to `get_post_meta()`, which results in an empty `string` instead of `null` value if there is no meta stored for the given meta key.

https://github.com/pronamic/wp-pay-core/blob/a6f6c6cd2379f6c4b292804e7225e7101cc43cca/src/Payments/PaymentInfo.php#L440-L458

**Comment by rvdsteege** [comment]
Discussed with @remcotolsma at HQ. We'll resolve this by retrieving post meta with the `$single` parameter set to `false` and checking the number of results. For `0` results, we'll return `null` in `PaymentInfo::get_meta()`.

**Comment by remcotolsma** [comment]
We may need to check type, since `get_post_meta` returns `mixed`: https://developer.wordpress.org/reference/functions/get_post_meta/.

With all the filters in the meta functions you are never sure what it will return.

I could remember us doing something similar somewhere:

https://github.com/pronamic/wp-pay-core/blob/649ec6aff28464abd8ce9905431fcf6d84ed8f0e/src/AbstractDataStoreCPT.php#L205-L217

An 'empty' check as above might also be workable for now?
