### ISSUE TITLE
Discrepancy in the payment count

### ISSUE THREAD

**Issue by knit-pay** [pronamic/wp-pay-core#58]
Hello Team

One of my clients reported a Discrepancy in the payment count on the payment page. On the top, it's mentioned that there are 42 Pending Payments, but after clicking it, it's showing only 19 payments on the bottom. Due to some confidential data in this WordPress website, he is not ready to share admin login details. So I was not able to figure out the exact issue. Do you have any idea about the same, What could be the possible reason for this issue?

<a href="https://ibb.co/G0bcY8P"><img src="https://i.ibb.co/f2P46y0/Whats-App-Image-2022-02-28-at-2-45-59-PM.jpg" alt="Whats-App-Image-2022-02-28-at-2-45-59-PM" border="0"></a>

**Comment by knit-pay** [comment]
Thanks for the reply @remcotolsma 

I will get this checked and update you.

**Comment by knit-pay** [comment]
After running the provided query, the pending payment count is 42 and in the list, it's still showing only 19 payments.

**Comment by rvdsteege** [comment]
Then, as @remcotolsma said:

> If the results of this query match the actual number of payments, there must be a cache issue or plugin conflict.

You can check for example if there is a file `/wp-content/object-cache.php` and temporarily rename the file, so it will not be used. Does that resolve the issue? If so, then the object cache of the website is not functioning properly or needs to be cleared.

**Comment by remcotolsma** [comment]
I suspect it's caused by another plugin, the filter options at the top left don't seem to be WordPress by default. Maybe ask if the problem also occurs if the plugin that adds those filter options is disabled? I am not familiar with the `Add Filter`, `Reset Settings` buttons.

**Comment by knit-pay** [comment]
Thanks for your feedback.
As client could not share access to website, there is nothing much we can do to find the exact issue. For now I am closing the ticket, will let you know if any other client will report same issue.

**Comment by knit-pay** [comment]
Hello @remcotolsma and @rvdsteege 

The client himself found the cause of the issue. After clicking the Pending payment filter, when they choose to sort by customer name or sort by transaction id option, some payments get hidden. I think this is due to a blank transaction id or blank customer name in some payments. Ideally, payments with a blank customer name or transaction id should also be visible even after sorting. Can this be fixed?

**Comment by rvdsteege** [comment]
Thanks for the update, @knit-pay. I did some testing, and was able to reproduce the issue you mentioned.

Apparently, sorting by customer name doesn't work at all anymore, because the meta key needed for this is no longer stored for recent payments (has been [removed](https://github.com/pronamic/wp-pay-core/commit/b833592a0ea8bb8b56bfa3fc2d12fb474c1e5416#diff-ff0c610d2aa0723d1c362b1a43e023e1e2906abdf10d79b66f3f64d7f6d824f3L366) with all the changes to store less data in post meta).

We could fix sorting for the transaction ID, but that requires an extra JOIN in the SQL query. We've now experiences this can get difficult in sites with many payments.

We're now thinking of removing the sorting functionality of the **Transaction** and **Customer** columns. Search can be used instead, when looking for a payment with a specific transaction ID.

Do you have any use cases for sorting or would it be fine to remove the sorting for these columns?

**Comment by knit-pay** [comment]
Thanks for the update. yes, you are right, It will be a good idea to remove sorting by transaction id and customer name. I also think it's useless.
